from .cliente_controller import ClienteController
from .direccion_controller import DireccionController
from .producto_controller import ProductoController
from .pedido_controller import PedidoController
from .detalle_pedido_controller import DetallePedidoController
from .movimiento_stock_controller import MovimientoStockController
